import { IslandView } from "./views";

export enum ProductionBuilding {
  Unknown = 'Unknown',
  AdvancedCoffeeRoaster = 'Advanced Coffee Roaster',
  AdvancedCottonMill = 'Advanced Cotton Mill',
  AdvancedRumDistillery = 'Advanced Rum Distillery',
  AlpacaFarm = 'Alpaca Farm',
  Apiary = 'Apiary',
  ArcticGasMine = 'Arctic Gas Mine',
  ArtisanalKitchen = 'Artisanal Kitchen',
  AssemblyLineBiscuits = 'Assembly Line: Biscuits',
  AssemblyLineElevators = 'Assembly Line: Elevators',
  AssemblyLineTypewriters = 'Assembly Line: Typewriters',
  Bakery = 'Bakery',
  BearHuntingCabin = 'Bear Hunting Cabin',
  BicycleFactory = 'Bicycle Factory',
  BombinWeaver = 'Bombin Weaver',
  BrassSmeltery = 'Brass Smetlery',
  Brewery = 'Brewery',
  BrickDryHouse = 'Brick Dry-House',
  BrickFactory = 'Brick Factory',
  CabAssemblyLine = 'Cab Assembly Line',
  Cannery = 'Cannery',
  CaoutchoucPlantation = 'Caoutchouc Plantation',
  CaribouHuntingCabin = 'Caribou Hunting Cabin',
  CattleFarm = 'Cattle Farm',
  ChampagneCellar = 'Champagne Cellar',
  CharcoalKiln = 'Charcoal Kiln',
  ChemicalPlantEthanol = 'Chemical Plant: Ethanol',
  ChemicalPlantLacquer = 'Chemical Plant: Lacquer',
  ChemicalPlantLemonade = 'Chemical Plant: Lemonade',
  ChemicalPlantShampoo = 'Chemical Plant: Shampoo',
  ChemicalPlantSouvenirs = 'Chemical Plant: Souvenirs',
  Coachmakers = 'Coachmakers',
  ChocolateFactory = 'Chocolate Factory',
  CigarFactory = 'Cigar Factory',
  ClayPit = 'Clay Pit',
  Clockmakers = 'Clockmakers',
  CoalMine = 'Coal Mine',
  CocoaPlantation = 'Cocoa Plantation',
  CoffeePlantation = 'Coffee Plantation',
  CoffeeRoaster = 'Coffee Roaster',
  ConcreteFactory = 'Concrete Factory',
  CopperMine = 'Copper Mine',
  CornFarm = 'Corn Farm',
  CottonMill = 'Cotton Mill',
  CottonPlantation = 'Cotton Plantation',
  DynamiteFactory = 'Dynamite Factory',
  FeltProducer = 'Felt Producer',
  FilamentFactory = 'Filament Factory',
  Fishery = 'Fishery',
  FishOilFactory = 'Fish Oil Factory',
  FlourMill = 'Flour Mill',
  FrameworkKnitters = 'Framework Knitters',
  FriedPlantainKitchen = 'Fried Plantain Kitchen',
  FurDealer = 'Fur Dealer',
  Furnace = 'Furnace',
  Glassmakers = 'Glassmakers',
  GoatFarm = 'Goat Farm',
  Goldsmiths = 'Goldsmiths',
  GoldOreMine = 'Gold Ore Mine',
  GooseFarm = 'Goose Farm',
  GrainFarm = 'Grain Farm',
  GramophoneFactory = 'Gramophone Factory',
  HeavyWeaponsFactory = 'Heavy Weapons Factory',
  HibiscusFarm = 'Hibiscus Farm',
  HopFarm = 'Hop Farm',
  HuntingCabin = 'Hunting Cabin',
  HuskyFarm = 'Husky Farm',
  HuskySledFactory = 'Husky Sled Factory',
  IndigoFarm = 'Indigo Farm',
  IronMine = 'Iron Mine',
  Jewellers = 'Jewellers',
  LightBulbFactory = 'Light Bulb Factory',
  LimestoneQuarry = 'Limestone Mine',
  LinenMill = 'Linen Mill',
  LinseedFarm = 'Linseed Farm',
  LobsterFishery = 'Lobster Fishery',
  LumberjacksHut = 'Lumberjack\'s Hut',
  Malthouse = 'Malthouse',
  MarquetryWorkshop = 'Marquetry Workshop',
  MotorAssemblyLine = 'Motor Assembly Line',
  OilLampFactory = 'Oil Lamp Factory',
  OilRefinery = 'Oil Refinery',
  PaperMill = 'Paper Mill',
  ParkaFactory = 'Parka Factory',
  PearlFarm = 'Pearl Farm',
  PemmicanCookhouse = 'Pemmican Cookhouse',
  PigFarm = 'Pig Farm',
  PlantainPlantation = 'Plantain Plantation',
  PonchoDarner = 'Poncho Darner',
  PotatoFarm = 'Potato Farm',
  PrimeHuntingCabin = 'Prime Hunting Cabin',
  RedPepperFarm = 'Red Pepper Farm',
  RenderingWorks = 'Rendering Works',
  RumDistillery = 'Rum Distillery',
  Sailmakers = 'Sailmakers',
  SaltpeterWorks = 'Saltpeter Works',
  SaltWorks = 'SaltWorks',
  SandMine = 'Sand Mine',
  Sawmill = 'Sawmill',
  SchnappsDistillery = 'Schnapps Distillery',
  SealHuntingDocks = 'Seal Hunting Docks',
  SewingMachineFactory = 'Sewing Machine Factory',
  SheepFarm = 'Sheep Farm',
  Slaughterhouse = 'Slaughterhouse',
  SledFrameFactory = 'Sled Frame Factory',
  SleepingBagFactory = 'Sleeping Bag Factory',
  SoapFactory = 'Soap Factory',
  SpectacleFactory = 'Spectacle Factory',
  SpiceFarm = 'Spice Farm',
  Steelworks = 'Steelworks',
  SugarCanePlantation = 'Sugar Cane Plantation',
  SugarRefinery = 'Sugar Refinery',
  TailorsShop = 'Tailor\'s Shop',
  TapestryLooms = 'Tapestry Looms',
  TeaSpicer = 'Tea Spicer',
  TeffFarm = 'Teff Farm',
  TelephoneManufacturer = 'Telephone Manufacturer',
  TobaccoPlantation = 'Tobacco Plantation',
  TortillaMaker = 'Tortilla Maker',
  Vineyard = 'Vineyard',
  WeaponFactory = 'Weapon Factory',
  WhalingStation = 'Whaling Station',
  WindowMakers = 'Window Makers',
  ZincMine = 'Zinc Mine',
};

export enum ProductionType {
  Mine = 'Mine',
  Factory = 'Factory',
  PlantFarm = 'Plant Farm',
  AnimalFarm = 'Animal Farm',
  HuntingCabin = 'Hunting Cabin',
  Orchard = 'Orchard',
  Oil = 'Oil',
};

export enum Good {
  Unknown = 'Unknown',
  AdvancedWeapons = 'Advanced Weapons',
  AlpacaWool = 'Alpaca Wool',
  AluminiumProfiles = 'Aluminium Profiles',
  ArcticGas = 'Arctic Gas',
  Bauxite = 'Bauxite',
  BearFur = 'Bear Fur',
  Beef = 'Beef',
  Beer = 'Beer',
  Beeswax = 'Beeswax',
  Biscuits = 'Biscuits',
  Bombs = 'Bombs',
  BowlerHats = 'Bowler Hats',
  Brass = 'Brass',
  Bread = 'Bread',
  Bricks = 'Bricks',
  CamphorWax = 'Camphor Wax',
  CannedFood = 'Canned Food',
  Caoutchouc = 'Caoutchouc',
  CaribouMeat = 'Caribou Meat',
  Cement = 'Cement',
  Champagne = 'Champagne',
  Chocolate = 'Chocolate',
  Cigars = 'Cigars',
  Cinnamon = 'Cinnamon',
  Citrus = 'Citrus',
  Clay = 'Clay',
  Chassis = 'Chassis',
  Coal = 'Coal',
  Cocoa = 'Cocoa',
  CoconutOil = 'Coconut Oil',
  Coffee = 'Coffee',
  CoffeeBeans = 'Coffee Beans',
  Copper = 'Copper',
  Corn = 'Corn',
  Cotton = 'Cotton',
  CottonFabric = 'Cotton Fabric',
  Dynamite = 'Dynamite',
  Elevators = 'Elevators',
  Ethanol = 'Ethanol',
  Felt = 'Felt',
  Filaments = 'Filaments',
  Fish = 'Fish',
  FishOil = 'Fish Oil',
  Flour = 'Flour',
  FriedPlantains = 'Fried Plantains',
  FurCoats = 'Fur Coats',
  Furs = 'Furs',
  Glass = 'Glass',
  Glasses = 'Glasses',
  GoatMilk = 'Goat Milk',
  Gold = 'Gold',
  GoldOre = 'Gold Ore',
  GooseFeathers = 'Goose Feathers',
  Goulash = 'Goulash',
  Grain = 'Grain',
  Grapes = 'Grapes',
  Gramophones = 'Gramophones',
  Helium = 'Helium',
  Herbs = 'Herbs',
  HibiscusPetals = 'Hibiscus Petals',
  HibiscusTea = 'Hibiscus Tea',
  Hops = 'Hops',
  Huskies = 'Huskies',
  HuskySleds = 'Husky Sleds',
  IceCream = 'Ice Cream',
  IndigoDye = 'Indigo Dye',
  Iron = 'Iron',
  Jam = 'Jam',
  Jewellery = 'Jewellery',
  Lacquer = 'Lacquer',
  LeatherBoots = 'Leather Boots',
  Lemonade = 'Lemonade',
  LightBulbs = 'Light Bulbs',
  Linen = 'Linen',
  Linseed = 'Linseed',
  Lobster = 'Lobster',
  Malt = 'Malt',
  Milk = 'Milk',
  Minerals = 'Minerals',
  MudBricks = 'Mud Bricks',
  NanduFeathers = 'Nandu Feathers',
  NanduLeather = 'Nandu Leather',
  Oil = 'Oil',
  OilLamps = 'Oil Lamps',
  Pamphlets = 'Pamphlets',
  Paper = 'Paper',
  Parkas = 'Parkas',
  Pearls = 'Pearls',
  Pemmican = 'Pemmican',
  PennyFarthings = 'Penny Farthings',
  Perfumes = 'Perfumes',
  Pigs = 'Pigs',
  Plantains = 'Plantains',
  PocketWatches = 'Pocket Watches',
  Ponchos = 'Ponchos',
  Potatoes = 'Potatoes',
  QuartzSand = 'Quartz Sand',
  RedPeppers = 'Red Peppers',
  ReinforcedConcrete = 'Reinforced Concrete',
  Resin = 'Resin',
  Rum = 'Rum',
  Sails = 'Sails',
  Salt = 'Salt',
  Saltpetre = 'Saltpetre',
  Sausages = 'Sausages',
  Schnapps = 'Schnapps',
  SealSkin = 'Seal Skin',
  SewingMachines = 'Sewing Machines',
  Shampoo = 'Shampoo',
  Sleds = 'Sleds',
  SleepingBags = 'Sleeping Bags',
  Soap = 'Soap',
  Souvenirs = 'Souvenirs',
  Spices = 'Spices',
  SteamCarriages = 'Steam Carriages',
  SteamMotors = 'Steam Motors',
  Steel = 'Steel',
  SteelBeams = 'Steel Beams',
  Sugar = 'Sugar',
  SugarCane = 'Sugar Cane',
  TailoredSuits = 'Tailored Suits',
  Tallow = 'Tallow',
  Tapestries = 'Tapestries',
  Teff = 'Teff',
  Telephones = 'Telephones',
  Timber = 'Timber',
  Tobacco = 'Tobacco',
  Tortillas = 'Tortillas',
  Toys = 'Toys',
  Typewriters = 'Typewriters',
  Violins = 'Violins',
  WaterDrop = 'Water Drop',
  Weapons = 'Weapons',
  WhaleOil = 'Whale Oil',
  Windows = 'Windows',
  Wood = 'Wood',
  WoodVeneers = 'Wood Veneers',
  Wool = 'Wool',
  WorkClothes = 'Work Clothes',
  Zinc = 'Zinc',
};

export enum BoostType {
  None = 'None',
  Electricity = 'Electricity',
  TracktorBarn = 'Tracktor Barn',
  Fertilizer = 'Fertilizer',
  Silo = 'Silo',
};

export enum DepartmentOfLaborPolicy {
  None = 'None',
  LandReformAct = 'Land Reform Act',
  SkilledLaborAct = 'Skilled Labor Act',
  GalvanicGrantsAct = 'Galvanic Grants Act',
  FactoryInspectionsAct = 'Factory Inspections Act',
  UnionSubsidiesAct = 'Union Subsidies Act',
};

export enum Region {
  Unknown = 'Unknown',
  OldWorld = 'Old World',
  NewWorld = 'New World',
  CapeTrelawney = 'Cape Trelawney',
  Arctic = 'The Arctic',
  Enbesa = 'Enbesa',
};

export interface Model { };

export interface ExtraGoodModel extends Model {
  good: Good;
  rateNumerator?: number,
  rateDenominator?: number,
};

export interface ProductionLineModel extends Model {
  building: ProductionBuilding;
  good: Good;
  numBuildings: number;
  boosts?: BoostType[];
  hasTradeUnion?: boolean;
  tradeUnionItemsBonus?: number;
  extraGoods: ExtraGoodModel[];
  inRangeOfLocalDepartment?: boolean;
};

export interface IslandModel extends Model {
  name: string;
  region?: Region;
  productionLines: ProductionLineModel[];
  dolPolicy?: DepartmentOfLaborPolicy;
};

export interface WorldModel extends Model {
  tradeUnionBonus?: number;
  islands: IslandModel[];
};

export const BASE_EXTRA_GOOD_MODEL: ExtraGoodModel = {
  good: Good.Unknown,
  rateNumerator: 1,
  rateDenominator: 1,
};

export const DEFAULT_EXTRA_GOOD_MODEL: ExtraGoodModel = {
  good: Good.Unknown,
  rateNumerator: 1,
  rateDenominator: 1,
};

export const BASE_PRODUCTION_LINE_MODEL: ProductionLineModel = {
  building: ProductionBuilding.Unknown,
  good: Good.Unknown,
  numBuildings: 1,
  extraGoods: [],
};

export const DEFAULT_PRODUCTION_LINE_MODEL: ProductionLineModel = {
  building: ProductionBuilding.Unknown,
  good: Good.Unknown,
  numBuildings: 0,
  boosts: [],
  hasTradeUnion: false,
  tradeUnionItemsBonus: 0.0,
  extraGoods: [],
  inRangeOfLocalDepartment: false,
};

export const BASE_ISLAND_MODEL: IslandModel = {
  name: 'UNNAMED_ISLAND',
  productionLines: [],
};

export const DEFAULT_ISLAND_MODEL: IslandModel = {
  name: '',
  region: Region.OldWorld,
  productionLines: [],
  dolPolicy: DepartmentOfLaborPolicy.None,
};

export const BASE_WORLD_MODEL: WorldModel = {
  islands: []
};

export const DEFAULT_WORLD_MODEL: WorldModel = {
  tradeUnionBonus: 0.0,
  islands: [],
};

export interface ProductionInfo {
  building: ProductionBuilding;
  processingTimeSeconds: number;
  productionType: ProductionType;
  good: Good;
  inputGoods?: Good[];
  allowedRegions: Region[];
  requiresElectricity?: boolean;
};

export const improvedByLandReformAct = new Set<ProductionBuilding>([
  ProductionBuilding.GrainFarm,
  ProductionBuilding.HopFarm,
  ProductionBuilding.PotatoFarm,
  ProductionBuilding.RedPepperFarm,
  ProductionBuilding.Vineyard,
  ProductionBuilding.SheepFarm,
  ProductionBuilding.PigFarm,
  ProductionBuilding.CattleFarm,
]);

export const improvedBySkilledLaborAct = new Set<ProductionBuilding>([
  ProductionBuilding.Steelworks,
  ProductionBuilding.Furnace,
  ProductionBuilding.CharcoalKiln,
  ProductionBuilding.WeaponFactory,
  ProductionBuilding.HeavyWeaponsFactory,
  ProductionBuilding.Steelworks,
  ProductionBuilding.CabAssemblyLine,
  ProductionBuilding.BrassSmeltery,
  ProductionBuilding.OilRefinery,
  ProductionBuilding.AssemblyLineElevators,
  ProductionBuilding.AssemblyLineBiscuits,
  ProductionBuilding.AssemblyLineTypewriters,
  ProductionBuilding.ChemicalPlantShampoo,
  ProductionBuilding.ChemicalPlantLemonade,
  ProductionBuilding.ChemicalPlantSouvenirs,
  ProductionBuilding.ChemicalPlantLacquer,
]);

export function getExtraGoodsModifier(productionBuilding: ProductionBuilding, good: Good, island: IslandView): number {
  const productionInfo = lookupProductionInfo(productionBuilding);
  if (productionInfo == null || good != productionInfo.good) {
    return 1.0;
  } else if (improvedByLandReformAct.has(productionBuilding) && island.dolPolicy == DepartmentOfLaborPolicy.LandReformAct) {
    return 1.5;
  } else if (improvedBySkilledLaborAct.has(productionBuilding) && island.dolPolicy == DepartmentOfLaborPolicy.SkilledLaborAct) {
    return 1. + 1. / 3.;
  } else {
    return 1.0;
  }
}

export const buildingInfo: ProductionInfo[] = [
  {
    building: ProductionBuilding.AdvancedCoffeeRoaster,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Coffee,
    inputGoods: [Good.Malt],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.AdvancedCottonMill,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.CottonFabric,
    inputGoods: [Good.Wool],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.AdvancedRumDistillery,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Rum,
    inputGoods: [Good.Potatoes],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.AlpacaFarm,
    processingTimeSeconds: 30,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.AlpacaWool,
  },
  {
    building: ProductionBuilding.Apiary,
    processingTimeSeconds: 30,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.Beeswax,
  },
  {
    building: ProductionBuilding.ArcticGasMine,
    processingTimeSeconds: 4.5 * 60,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.Arctic],
    good: Good.ArcticGas,
  },
  {
    building: ProductionBuilding.ArtisanalKitchen,
    processingTimeSeconds: 120,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Goulash,
    inputGoods: [Good.Beef, Good.RedPeppers],
  },
  {
    building: ProductionBuilding.AssemblyLineBiscuits,
    processingTimeSeconds: 15,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Biscuits,
    inputGoods: [Good.Tallow, Good.Flour, Good.Citrus],
  },
  {
    building: ProductionBuilding.AssemblyLineElevators,
    processingTimeSeconds: 15,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Elevators,
    inputGoods: [Good.Steel, Good.WoodVeneers, Good.SteamMotors],
  },
  {
    building: ProductionBuilding.AssemblyLineTypewriters,
    processingTimeSeconds: 15,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Typewriters,
    inputGoods: [Good.Steel, Good.Brass, Good.Lacquer],
  },
  {
    building: ProductionBuilding.Bakery,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Bread,
    inputGoods: [Good.Flour],
  },
  {
    building: ProductionBuilding.BearHuntingCabin,
    processingTimeSeconds: 90,
    productionType: ProductionType.HuntingCabin,
    allowedRegions: [Region.Arctic],
    good: Good.BearFur,
  },
  {
    building: ProductionBuilding.BicycleFactory,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.PennyFarthings,
    inputGoods: [Good.Steel, Good.Caoutchouc],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.BombinWeaver,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.BowlerHats,
    inputGoods: [Good.CottonFabric, Good.Felt],
  },
  {
    building: ProductionBuilding.BrassSmeltery,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Brass,
    inputGoods: [Good.Copper, Good.Zinc],
  },
  {
    building: ProductionBuilding.Brewery,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Beer,
    inputGoods: [Good.Malt, Good.Hops],
  },
  {
    building: ProductionBuilding.BrickDryHouse,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Enbesa],
    good: Good.MudBricks,
    inputGoods: [Good.Clay, Good.Teff],
  },
  {
    building: ProductionBuilding.BrickFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.Bricks,
    inputGoods: [Good.Clay],
  },
  {
    building: ProductionBuilding.CabAssemblyLine,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.SteamCarriages,
    inputGoods: [Good.SteamMotors, Good.Chassis],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.Cannery,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.CannedFood,
    inputGoods: [Good.Goulash, Good.Iron],
  },
  {
    building: ProductionBuilding.CaoutchoucPlantation,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.Caoutchouc,
  },
  {
    building: ProductionBuilding.CaribouHuntingCabin,
    processingTimeSeconds: 60,
    productionType: ProductionType.HuntingCabin,
    allowedRegions: [Region.Arctic],
    good: Good.CaribouMeat,
  },
  {
    building: ProductionBuilding.CattleFarm,
    processingTimeSeconds: 120,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.Beef,
  },
  {
    building: ProductionBuilding.ChampagneCellar,
    processingTimeSeconds: 30,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Champagne,
    inputGoods: [Good.Grapes, Good.Glass],
  },
  {
    building: ProductionBuilding.CharcoalKiln,
    processingTimeSeconds: 30,
    productionType: ProductionType.Orchard,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld, Region.Arctic],
    good: Good.Coal,
  },
  {
    building: ProductionBuilding.ChemicalPlantEthanol,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Ethanol,
    inputGoods: [Good.Wood, Good.Corn],
  },
  {
    building: ProductionBuilding.ChemicalPlantShampoo,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Shampoo,
    inputGoods: [Good.CoconutOil, Good.Cinnamon, Good.Soap],
  },
  {
    building: ProductionBuilding.ChemicalPlantLemonade,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Lemonade,
    inputGoods: [Good.Sugar, Good.Citrus, Good.Saltpetre],
  },
  {
    building: ProductionBuilding.ChemicalPlantSouvenirs,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Souvenirs,
    inputGoods: [Good.CamphorWax, Good.Glass, Good.Cotton],
  },
  {
    building: ProductionBuilding.ChemicalPlantLacquer,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Lacquer,
    inputGoods: [Good.QuartzSand, Good.Resin, Good.Ethanol],
  },
  {
    building: ProductionBuilding.ChocolateFactory,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Chocolate,
    inputGoods: [Good.Cocoa, Good.Sugar],
  },
  {
    building: ProductionBuilding.CigarFactory,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Cigars,
    inputGoods: [Good.Tobacco, Good.WoodVeneers],
  },
  {
    building: ProductionBuilding.ClayPit,
    processingTimeSeconds: 30,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.Clay,
  },
  {
    building: ProductionBuilding.Clockmakers,
    processingTimeSeconds: 45,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.PocketWatches,
    inputGoods: [Good.Gold, Good.Glass],
  },
  {
    building: ProductionBuilding.Coachmakers,
    processingTimeSeconds: 120,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Chassis,
    inputGoods: [Good.Wood, Good.Caoutchouc],
  },
  {
    building: ProductionBuilding.CoalMine,
    processingTimeSeconds: 15,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Coal,
  },
  {
    building: ProductionBuilding.CocoaPlantation,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.Cocoa,
  },
  {
    building: ProductionBuilding.CoffeePlantation,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.CoffeeBeans,
  },
  {
    building: ProductionBuilding.CoffeeRoaster,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Coffee,
    inputGoods: [Good.CoffeeBeans],
  },
  {
    building: ProductionBuilding.ConcreteFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.ReinforcedConcrete,
    inputGoods: [Good.Steel, Good.Cement],
  },
  {
    building: ProductionBuilding.CopperMine,
    processingTimeSeconds: 30,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Copper,
  },
  {
    building: ProductionBuilding.CornFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.Corn,
  },
  {
    building: ProductionBuilding.CottonMill,
    processingTimeSeconds: 30,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.CottonFabric,
    inputGoods: [Good.Cotton],
  },
  {
    building: ProductionBuilding.CottonPlantation,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.Cotton,
  },
  {
    building: ProductionBuilding.DynamiteFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Dynamite,
    inputGoods: [Good.Tallow, Good.Saltpetre],
  },
  {
    building: ProductionBuilding.FilamentFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Filaments,
    inputGoods: [Good.Coal],
  },
  {
    building: ProductionBuilding.Fishery,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Fish,
  },
  {
    building: ProductionBuilding.FishOilFactory,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.FishOil,
  },
  {
    building: ProductionBuilding.FlourMill,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Flour,
    inputGoods: [Good.Grain],
  },
  {
    building: ProductionBuilding.FrameworkKnitters,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.WorkClothes,
    inputGoods: [Good.Wool],
  },
  {
    building: ProductionBuilding.FriedPlantainKitchen,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.FriedPlantains,
    inputGoods: [Good.Plantains, Good.FishOil],
  },
  {
    building: ProductionBuilding.FurDealer,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.FurCoats,
    inputGoods: [Good.Wool, Good.Furs],
  },
  {
    building: ProductionBuilding.Furnace,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Steel,
    inputGoods: [Good.Iron, Good.Coal],
  },
  {
    building: ProductionBuilding.Glassmakers,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Glass,
    inputGoods: [Good.QuartzSand],
  },
  {
    building: ProductionBuilding.GoatFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.GoatMilk,
  },
  {
    building: ProductionBuilding.GoldOreMine,
    processingTimeSeconds: 150,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.NewWorld],
    good: Good.GoldOre,
  },
  {
    building: ProductionBuilding.Goldsmiths,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Gold,
    inputGoods: [Good.GoldOre, Good.Coal],
  },
  {
    building: ProductionBuilding.GooseFarm,
    processingTimeSeconds: 120,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.Arctic],
    good: Good.GooseFeathers,
  },
  {
    building: ProductionBuilding.GrainFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Grain,
  },
  {
    building: ProductionBuilding.GramophoneFactory,
    processingTimeSeconds: 120,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Gramophones,
    inputGoods: [Good.WoodVeneers, Good.Brass],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.HeavyWeaponsFactory,
    processingTimeSeconds: 120,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.AdvancedWeapons,
    inputGoods: [Good.Dynamite, Good.Steel],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.HibiscusFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.HibiscusPetals,
  },
  {
    building: ProductionBuilding.HopFarm,
    processingTimeSeconds: 90,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Hops,
  },
  {
    building: ProductionBuilding.HuntingCabin,
    processingTimeSeconds: 60,
    productionType: ProductionType.HuntingCabin,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Furs,
  },
  {
    building: ProductionBuilding.HuskyFarm,
    processingTimeSeconds: 120,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.Arctic],
    good: Good.Huskies,
  },
  {
    building: ProductionBuilding.HuskySledFactory,
    processingTimeSeconds: 120,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.HuskySleds,
    inputGoods: [Good.Huskies, Good.Sleds],
  },
  {
    building: ProductionBuilding.IndigoFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.IndigoDye,
  },
  {
    building: ProductionBuilding.IronMine,
    processingTimeSeconds: 15,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.Iron,
  },
  {
    building: ProductionBuilding.Jewellers,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Jewellery,
    inputGoods: [Good.Gold, Good.Pearls],
  },
  {
    building: ProductionBuilding.LightBulbFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.LightBulbs,
    inputGoods: [Good.Filaments, Good.Glass],
  },
  {
    building: ProductionBuilding.LimestoneQuarry,
    processingTimeSeconds: 30,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Cement,
  },
  {
    building: ProductionBuilding.LinenMill,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Enbesa],
    good: Good.Linen,
    inputGoods: [Good.Linseed],
  },
  {
    building: ProductionBuilding.LinseedFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.Linseed,
  },
  {
    building: ProductionBuilding.LobsterFishery,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Enbesa],
    good: Good.Lobster,
  },
  {
    building: ProductionBuilding.LumberjacksHut,
    processingTimeSeconds: 15,
    productionType: ProductionType.Orchard,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.Wood,
  },
  {
    building: ProductionBuilding.Malthouse,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Malt,
    inputGoods: [Good.Grain],
  },
  {
    building: ProductionBuilding.MarquetryWorkshop,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.WoodVeneers,
    inputGoods: [Good.Wood],
  },
  {
    building: ProductionBuilding.MotorAssemblyLine,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.SteamMotors,
    inputGoods: [Good.Steel, Good.Brass],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.OilLampFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.OilLamps,
    inputGoods: [Good.Brass, Good.WhaleOil],
  },
  {
    building: ProductionBuilding.OilRefinery,
    processingTimeSeconds: 15,
    productionType: ProductionType.Oil,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.Oil,
  },
  {
    building: ProductionBuilding.PaperMill,
    processingTimeSeconds: 15,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Enbesa],
    good: Good.Paper,
    inputGoods: [Good.Wood],
  },
  {
    building: ProductionBuilding.ParkaFactory,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.Parkas,
    inputGoods: [Good.BearFur, Good.SealSkin],
  },
  {
    building: ProductionBuilding.PearlFarm,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Pearls,
  },
  {
    building: ProductionBuilding.PemmicanCookhouse,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.Pemmican,
    inputGoods: [Good.WhaleOil, Good.CaribouMeat],
  },
  {
    building: ProductionBuilding.PigFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Pigs,
  },
  {
    building: ProductionBuilding.PlantainPlantation,
    processingTimeSeconds: 30,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.Plantains,
  },
  {
    building: ProductionBuilding.PonchoDarner,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Ponchos,
    inputGoods: [Good.AlpacaWool],
  },
  {
    building: ProductionBuilding.PotatoFarm,
    processingTimeSeconds: 30,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Potatoes,
  },
  {
    building: ProductionBuilding.PrimeHuntingCabin,
    processingTimeSeconds: 15,
    productionType: ProductionType.HuntingCabin,
    allowedRegions: [Region.Arctic],
    good: Good.Furs,
  },
  {
    building: ProductionBuilding.RedPepperFarm,
    processingTimeSeconds: 120,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.RedPeppers,
  },
  {
    building: ProductionBuilding.RenderingWorks,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Tallow,
    inputGoods: [Good.Pigs],
  },
  {
    building: ProductionBuilding.RumDistillery,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Rum,
    inputGoods: [Good.SugarCane, Good.Wood],
  },
  {
    building: ProductionBuilding.Sailmakers,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Sails,
    inputGoods: [Good.Wool],
  },
  {
    building: ProductionBuilding.SaltWorks,
    processingTimeSeconds: 90,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.Enbesa],
    good: Good.Salt,
  },
  {
    building: ProductionBuilding.SaltpeterWorks,
    processingTimeSeconds: 120,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Saltpetre,
  },
  {
    building: ProductionBuilding.SandMine,
    processingTimeSeconds: 30,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.QuartzSand,
  },
  {
    building: ProductionBuilding.Sawmill,
    processingTimeSeconds: 15,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld, Region.Arctic],
    good: Good.Timber,
    inputGoods: [Good.Wood],
  },
  {
    building: ProductionBuilding.SealHuntingDocks,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.SealSkin,
  },
  {
    building: ProductionBuilding.SchnappsDistillery,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Schnapps,
    inputGoods: [Good.Potatoes],
  },
  {
    building: ProductionBuilding.SewingMachineFactory,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.SewingMachines,
    inputGoods: [Good.Steel, Good.Wood],
  },
  {
    building: ProductionBuilding.SheepFarm,
    processingTimeSeconds: 30,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Wool,
  },
  {
    building: ProductionBuilding.Slaughterhouse,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Sausages,
    inputGoods: [Good.Pigs],
  },
  {
    building: ProductionBuilding.SledFrameFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.Sleds,
    inputGoods: [Good.SealSkin, Good.Wood],
  },
  {
    building: ProductionBuilding.SleepingBagFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.SleepingBags,
    inputGoods: [Good.SealSkin, Good.GooseFeathers],
  },
  {
    building: ProductionBuilding.SoapFactory,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Soap,
    inputGoods: [Good.Tallow],
  },
  {
    building: ProductionBuilding.SpectacleFactory,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Glasses,
    inputGoods: [Good.Glass, Good.Brass],
  },
  {
    building: ProductionBuilding.SpiceFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.Spices,
  },
  {
    building: ProductionBuilding.Steelworks,
    processingTimeSeconds: 45,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.SteelBeams,
    inputGoods: [Good.Steel],
  },
  {
    building: ProductionBuilding.SugarCanePlantation,
    processingTimeSeconds: 30,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.SugarCane,
  },
  {
    building: ProductionBuilding.SugarRefinery,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Sugar,
    inputGoods: [Good.SugarCane],
  },
  {
    building: ProductionBuilding.TapestryLooms,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Enbesa],
    good: Good.Tapestries,
    inputGoods: [Good.Linen, Good.IndigoDye],
  },
  {
    building: ProductionBuilding.TailorsShop,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.TailoredSuits,
    inputGoods: [Good.CottonFabric, Good.Linen],
  },
  {
    building: ProductionBuilding.TeaSpicer,
    processingTimeSeconds: 90,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.HibiscusTea,
    inputGoods: [Good.HibiscusPetals],
  },
  {
    building: ProductionBuilding.TeffFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.Teff,
  },
  {
    building: ProductionBuilding.TelephoneManufacturer,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Telephones,
    inputGoods: [Good.Filaments, Good.WoodVeneers],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.TobaccoPlantation,
    processingTimeSeconds: 120,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.Tobacco,
  },
  {
    building: ProductionBuilding.TortillaMaker,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Tortillas,
    inputGoods: [Good.Corn, Good.Beef],
  },
  {
    building: ProductionBuilding.Vineyard,
    processingTimeSeconds: 120,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Grapes,
  },
  {
    building: ProductionBuilding.WeaponFactory,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Weapons,
    inputGoods: [Good.Steel],
  },
  {
    building: ProductionBuilding.WhalingStation,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.WhaleOil,
  },
  {
    building: ProductionBuilding.WindowMakers,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Windows,
    inputGoods: [Good.Glass, Good.Wood],
  },
  {
    building: ProductionBuilding.ZincMine,
    processingTimeSeconds: 30,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Zinc,
  },
];

const builingsToInfo = new Map<ProductionBuilding, ProductionInfo>(buildingInfo.map(i => [i.building, i]));

export function lookupProductionInfo(building: ProductionBuilding): ProductionInfo | undefined {
  return builingsToInfo.get(building);
};

export function requiresElectricity(building: ProductionBuilding): boolean {
  return builingsToInfo.get(building)?.requiresElectricity ?? false;
}

export function lookupAllowedBoosts(building: ProductionBuilding): BoostType[] {
  const info = lookupProductionInfo(building);
  if (!info || info.allowedRegions.indexOf(Region.Enbesa) != -1) {
    return [];
  }
  if (info.productionType == ProductionType.AnimalFarm) {
    return [BoostType.Silo];
  } else if (info.productionType == ProductionType.Factory) {
    return [BoostType.Electricity];
  } else if (info.productionType == ProductionType.Mine) {
    return [BoostType.Electricity];
  } else if (info.productionType == ProductionType.PlantFarm) {
    return [BoostType.TracktorBarn, BoostType.Fertilizer];
  }
  return [];
}

const goodsToIconUrl = new Map<Good, string>([
  [Good.Unknown, ''],
  [Good.AdvancedWeapons, 'https://static.wikia.nocookie.net/anno1800/images/3/30/Advanced_weapons.png'],
  [Good.AlpacaWool, 'https://static.wikia.nocookie.net/anno1800/images/a/a6/Alpaca_wool.png'],
  [Good.AluminiumProfiles, 'https://static.wikia.nocookie.net/anno1800/images/2/24/Aluminium_Profiles.png'],
  [Good.ArcticGas, 'https://static.wikia.nocookie.net/anno1800/images/e/e5/Arctic_Gas.png'],
  [Good.Bauxite, 'https://static.wikia.nocookie.net/anno1800/images/1/11/Bauxite.png'],
  [Good.BearFur, 'https://static.wikia.nocookie.net/anno1800/images/7/72/Bear_Fur.png'],
  [Good.Beef, 'https://static.wikia.nocookie.net/anno1800/images/a/af/Beef.png'],
  [Good.Beer, 'https://static.wikia.nocookie.net/anno1800/images/b/b3/Beer.png'],
  [Good.Beeswax, 'https://static.wikia.nocookie.net/anno1800/images/7/70/Icon_beeswax_0.png'],
  [Good.Biscuits, 'https://static.wikia.nocookie.net/anno1800/images/f/f5/Biscuits.png'],
  [Good.Bombs, 'https://static.wikia.nocookie.net/anno1800/images/c/cc/Bombs.png'],
  [Good.BowlerHats, 'https://static.wikia.nocookie.net/anno1800/images/d/db/Bowler_hats.png'],
  [Good.Brass, 'https://static.wikia.nocookie.net/anno1800/images/d/de/Brass.png'],
  [Good.Bread, 'https://static.wikia.nocookie.net/anno1800/images/e/e1/Bread.png'],
  [Good.Bricks, 'https://static.wikia.nocookie.net/anno1800/images/f/ff/Bricks.png'],
  [Good.CamphorWax, 'https://static.wikia.nocookie.net/anno1800/images/3/30/Camphor_Wax.png'],
  [Good.CannedFood, 'https://static.wikia.nocookie.net/anno1800/images/c/c8/Canned_food.png'],
  [Good.Caoutchouc, 'https://static.wikia.nocookie.net/anno1800/images/5/52/Caoutchouc.png'],
  [Good.CaribouMeat, 'https://static.wikia.nocookie.net/anno1800/images/e/e9/Caribou_Meat.png'],
  [Good.Cement, 'https://static.wikia.nocookie.net/anno1800/images/d/de/Cement.png'],
  [Good.Champagne, 'https://static.wikia.nocookie.net/anno1800/images/0/05/Champagne.png'],
  [Good.Chocolate, 'https://static.wikia.nocookie.net/anno1800/images/d/df/Chocolate.png'],
  [Good.Cigars, 'https://static.wikia.nocookie.net/anno1800/images/8/87/Cigars.png'],
  [Good.Cinnamon, 'https://static.wikia.nocookie.net/anno1800/images/1/1b/Cinnamon.png'],
  [Good.Citrus, 'https://static.wikia.nocookie.net/anno1800/images/b/b4/Citrus.png'],
  [Good.Clay, 'https://static.wikia.nocookie.net/anno1800/images/a/a2/Clay.png'],
  [Good.Chassis, 'https://static.wikia.nocookie.net/anno1800/images/d/dd/Chassis.png'],
  [Good.Coal, 'https://static.wikia.nocookie.net/anno1800/images/a/a7/Coal.png'],
  [Good.Cocoa, 'https://static.wikia.nocookie.net/anno1800/images/8/8d/Cocoa.png'],
  [Good.CoconutOil, 'https://static.wikia.nocookie.net/anno1800/images/e/e6/Coconut_Oil.png'],
  [Good.Coffee, 'https://static.wikia.nocookie.net/anno1800/images/e/e9/Coffee.png'],
  [Good.CoffeeBeans, 'https://static.wikia.nocookie.net/anno1800/images/6/6e/Coffee_beans.png'],
  [Good.Copper, 'https://static.wikia.nocookie.net/anno1800/images/1/12/Copper.png'],
  [Good.Corn, 'https://static.wikia.nocookie.net/anno1800/images/f/f8/Corn.png'],
  [Good.Cotton, 'https://static.wikia.nocookie.net/anno1800/images/c/c3/Cotton.png'],
  [Good.CottonFabric, 'https://static.wikia.nocookie.net/anno1800/images/1/15/Cotton_fabric.png'],
  [Good.Dynamite, 'https://static.wikia.nocookie.net/anno1800/images/f/fc/Dynamite.png'],
  [Good.Elevators, 'https://static.wikia.nocookie.net/anno1800/images/d/db/Elevators.png'],
  [Good.Ethanol, 'https://static.wikia.nocookie.net/anno1800/images/9/95/Ethanol.png'],
  [Good.Felt, 'https://static.wikia.nocookie.net/anno1800/images/b/b0/Felt.png'],
  [Good.Filaments, 'https://static.wikia.nocookie.net/anno1800/images/d/d8/Filaments.png'],
  [Good.Fish, 'https://static.wikia.nocookie.net/anno1800/images/f/fb/Fish.png'],
  [Good.FishOil, 'https://static.wikia.nocookie.net/anno1800/images/e/ea/Fish_Oil.png'],
  [Good.Flour, 'https://static.wikia.nocookie.net/anno1800/images/e/e8/Flour.png'],
  [Good.FriedPlantains, 'https://static.wikia.nocookie.net/anno1800/images/5/58/Fried_plantains.png'],
  [Good.FurCoats, 'https://static.wikia.nocookie.net/anno1800/images/8/85/Fur_Coats.png'],
  [Good.Furs, 'https://static.wikia.nocookie.net/anno1800/images/8/88/Furs.png'],
  [Good.Glass, 'https://static.wikia.nocookie.net/anno1800/images/1/15/Glass.png'],
  [Good.Glasses, 'https://static.wikia.nocookie.net/anno1800/images/b/b4/Glasses.png'],
  [Good.GoatMilk, 'https://static.wikia.nocookie.net/anno1800/images/7/7b/Icon_goat_milk_0.png'],
  [Good.Gold, 'https://static.wikia.nocookie.net/anno1800/images/1/10/Gold.png'],
  [Good.GoldOre, 'https://static.wikia.nocookie.net/anno1800/images/f/f7/Gold_Ore.png'],
  [Good.GooseFeathers, 'https://static.wikia.nocookie.net/anno1800/images/8/82/Goose_Feathers.png'],
  [Good.Goulash, 'https://static.wikia.nocookie.net/anno1800/images/5/5e/Goulash.png'],
  [Good.Grain, 'https://static.wikia.nocookie.net/anno1800/images/6/66/Grain.png'],
  [Good.Grapes, 'https://static.wikia.nocookie.net/anno1800/images/3/39/Grapes.png'],
  [Good.Gramophones, 'https://static.wikia.nocookie.net/anno1800/images/0/0e/Gramophone.png'],
  [Good.Helium, 'https://static.wikia.nocookie.net/anno1800/images/5/57/Helium.png'],
  [Good.Herbs, 'https://static.wikia.nocookie.net/anno1800/images/7/79/Herbs.png'],
  [Good.HibiscusPetals, 'https://static.wikia.nocookie.net/anno1800/images/0/04/Icon_hibiscus_farm_0.png'],
  [Good.HibiscusTea, 'https://static.wikia.nocookie.net/anno1800/images/6/69/Icon_hibiscus_tea_0.png'],
  [Good.Hops, 'https://static.wikia.nocookie.net/anno1800/images/5/59/Hops.png'],
  [Good.Huskies, 'https://static.wikia.nocookie.net/anno1800/images/4/4b/Huskies.png'],
  [Good.HuskySleds, 'https://static.wikia.nocookie.net/anno1800/images/5/59/Husky_Sleds.png'],
  [Good.IceCream, 'https://static.wikia.nocookie.net/anno1800/images/5/5d/Ice_Cream.png'],
  [Good.IndigoDye, 'https://static.wikia.nocookie.net/anno1800/images/1/1b/Icon_indigo_0.png'],
  [Good.Iron, 'https://static.wikia.nocookie.net/anno1800/images/4/45/Iron.png'],
  [Good.Jam, 'https://static.wikia.nocookie.net/anno1800/images/f/fa/Jam.png'],
  [Good.Jewellery, 'https://static.wikia.nocookie.net/anno1800/images/7/7b/Jewelry.png'],
  [Good.Lacquer, 'https://static.wikia.nocookie.net/anno1800/images/4/4c/Lacquer.png'],
  [Good.LeatherBoots, 'https://static.wikia.nocookie.net/anno1800/images/c/c4/Icon_leather_shoes_0.png'],
  [Good.Lemonade, 'https://static.wikia.nocookie.net/anno1800/images/2/2a/Lemonade.png'],
  [Good.LightBulbs, 'https://static.wikia.nocookie.net/anno1800/images/0/06/Light_bulb.png'],
  [Good.Linen, 'https://static.wikia.nocookie.net/anno1800/images/9/9a/Icon_linen_fabric_0.png'],
  [Good.Linseed, 'https://static.wikia.nocookie.net/anno1800/images/6/65/Icon_linen_farm_0.png'],
  [Good.Lobster, 'https://static.wikia.nocookie.net/anno1800/images/9/91/Icon_seafood_0.png'],
  [Good.Malt, 'https://static.wikia.nocookie.net/anno1800/images/d/de/Malt.png'],
  [Good.Milk, 'https://static.wikia.nocookie.net/anno1800/images/9/92/Milk.png'],
  [Good.Minerals, 'https://static.wikia.nocookie.net/anno1800/images/1/10/Minerals.png'],
  [Good.MudBricks, 'https://static.wikia.nocookie.net/anno1800/images/a/ab/Icon_mud_bricks_0.png'],
  [Good.NanduFeathers, 'https://static.wikia.nocookie.net/anno1800/images/4/4c/Nandu_Feathers.png'],
  [Good.NanduLeather, 'https://static.wikia.nocookie.net/anno1800/images/f/fc/Nandu_Leather.png'],
  [Good.Oil, 'https://static.wikia.nocookie.net/anno1800/images/0/06/Oil.png'],
  [Good.OilLamps, 'https://static.wikia.nocookie.net/anno1800/images/5/57/Oil_Lamps.png'],
  [Good.Pamphlets, 'https://static.wikia.nocookie.net/anno1800/images/c/c5/Pamphlets.png'],
  [Good.Paper, 'https://static.wikia.nocookie.net/anno1800/images/1/1d/Icon_paper_0.png'],
  [Good.Parkas, 'https://static.wikia.nocookie.net/anno1800/images/d/d6/Parkas.png'],
  [Good.Pearls, 'https://static.wikia.nocookie.net/anno1800/images/7/76/Pearls.png'],
  [Good.Pemmican, 'https://static.wikia.nocookie.net/anno1800/images/3/33/Pemmican.png'],
  [Good.PennyFarthings, 'https://static.wikia.nocookie.net/anno1800/images/b/b9/High_wheeler.png'],
  [Good.Perfumes, 'https://static.wikia.nocookie.net/anno1800/images/7/71/Perfumes.png'],
  [Good.Pigs, 'https://static.wikia.nocookie.net/anno1800/images/e/e3/Pigs.png'],
  [Good.Plantains, 'https://static.wikia.nocookie.net/anno1800/images/c/c4/Plantains.png'],
  [Good.PocketWatches, 'https://static.wikia.nocookie.net/anno1800/images/b/be/Pocket_watch.png'],
  [Good.Ponchos, 'https://static.wikia.nocookie.net/anno1800/images/2/27/Poncho.png'],
  [Good.Potatoes, 'https://static.wikia.nocookie.net/anno1800/images/c/c2/Potato.png'],
  [Good.QuartzSand, 'https://static.wikia.nocookie.net/anno1800/images/5/50/Quartz_sand.png'],
  [Good.RedPeppers, 'https://static.wikia.nocookie.net/anno1800/images/c/cf/Red_peppers.png'],
  [Good.ReinforcedConcrete, 'https://static.wikia.nocookie.net/anno1800/images/7/7a/Reinforced_concrete.png'],
  [Good.Resin, 'https://static.wikia.nocookie.net/anno1800/images/2/2c/Resin.png'],
  [Good.Rum, 'https://static.wikia.nocookie.net/anno1800/images/6/61/Rum.png'],
  [Good.Sails, 'https://static.wikia.nocookie.net/anno1800/images/2/22/Sails.png'],
  [Good.Salt, 'https://static.wikia.nocookie.net/anno1800/images/7/77/Salt.png'],
  [Good.Saltpetre, 'https://static.wikia.nocookie.net/anno1800/images/d/d7/Saltpeter.png'],
  [Good.Sausages, 'https://static.wikia.nocookie.net/anno1800/images/a/a0/Sausages.png'],
  [Good.Schnapps, 'https://static.wikia.nocookie.net/anno1800/images/4/47/Schnapps.png'],
  [Good.SealSkin, 'https://static.wikia.nocookie.net/anno1800/images/d/df/Seal_Skin.png'],
  [Good.SewingMachines, 'https://static.wikia.nocookie.net/anno1800/images/f/ff/Sewing_machines.png'],
  [Good.Shampoo, 'https://static.wikia.nocookie.net/anno1800/images/b/bb/Shampoo.png'],
  [Good.Sleds, 'https://static.wikia.nocookie.net/anno1800/images/f/fc/Sleds.png'],
  [Good.SleepingBags, 'https://static.wikia.nocookie.net/anno1800/images/0/0a/Sleeping_Bags.png'],
  [Good.Soap, 'https://static.wikia.nocookie.net/anno1800/images/6/65/Soap.png'],
  [Good.Souvenirs, 'https://static.wikia.nocookie.net/anno1800/images/5/56/Souvenirs.png'],
  [Good.Spices, 'https://static.wikia.nocookie.net/anno1800/images/e/ec/Icon_spices_0.png'],
  [Good.SteamCarriages, 'https://static.wikia.nocookie.net/anno1800/images/7/7c/Steam_carriages.png'],
  [Good.SteamMotors, 'https://static.wikia.nocookie.net/anno1800/images/b/b9/Steam_motors.png'],
  [Good.Steel, 'https://static.wikia.nocookie.net/anno1800/images/c/c9/Steel.png'],
  [Good.SteelBeams, 'https://static.wikia.nocookie.net/anno1800/images/5/52/Steel_beams.png'],
  [Good.Sugar, 'https://static.wikia.nocookie.net/anno1800/images/a/a9/Sugar.png'],
  [Good.SugarCane, 'https://static.wikia.nocookie.net/anno1800/images/e/e8/Sugar_cane.png'],
  [Good.TailoredSuits, 'https://static.wikia.nocookie.net/anno1800/images/6/6d/Icon_suits_0.png'],
  [Good.Tallow, 'https://static.wikia.nocookie.net/anno1800/images/f/f7/Tallow.png'],
  [Good.Tapestries, 'https://static.wikia.nocookie.net/anno1800/images/1/12/Icon_tapestries_0.png'],
  [Good.Teff, 'https://static.wikia.nocookie.net/anno1800/images/1/18/Icon_teff_grass_0.png'],
  [Good.Telephones, 'https://static.wikia.nocookie.net/anno1800/images/f/f3/Icon_telephones_0.png'],
  [Good.Timber, 'https://static.wikia.nocookie.net/anno1800/images/7/71/Timber.png'],
  [Good.Tobacco, 'https://static.wikia.nocookie.net/anno1800/images/1/19/Tobacco.png'],
  [Good.Tortillas, 'https://static.wikia.nocookie.net/anno1800/images/d/d7/Tortilla.png'],
  [Good.Toys, 'https://static.wikia.nocookie.net/anno1800/images/3/37/Toys.png'],
  [Good.Typewriters, 'https://static.wikia.nocookie.net/anno1800/images/6/6c/Typewriters.png'],
  [Good.Violins, 'https://static.wikia.nocookie.net/anno1800/images/3/3f/Violins.png'],
  [Good.WaterDrop, 'https://static.wikia.nocookie.net/anno1800/images/9/9c/Water_Drop.png'],
  [Good.Weapons, 'https://static.wikia.nocookie.net/anno1800/images/a/ae/Weapons.png'],
  [Good.WhaleOil, 'https://static.wikia.nocookie.net/anno1800/images/f/f5/Whale_Oil.png'],
  [Good.Windows, 'https://static.wikia.nocookie.net/anno1800/images/b/ba/Windows.png'],
  [Good.Wood, 'https://static.wikia.nocookie.net/anno1800/images/d/df/Wood.png'],
  [Good.WoodVeneers, 'https://static.wikia.nocookie.net/anno1800/images/8/80/Wood_veneers.png'],
  [Good.Wool, 'https://static.wikia.nocookie.net/anno1800/images/3/34/Wool.png'],
  [Good.WorkClothes, 'https://static.wikia.nocookie.net/anno1800/images/e/e9/Work_clothes.png'],
  [Good.Zinc, 'https://static.wikia.nocookie.net/anno1800/images/c/cb/Zinc.png'],
]);

export function lookupGoodIconUrl(good: Good): string {
  return goodsToIconUrl.get(good)
    ?? 'https://static.wikia.nocookie.net/anno1800/images/c/ce/Sir_Archibald_Blake.png';
}

const productionBuildingToIconUrl = new Map<ProductionBuilding, string>(
  buildingInfo.map(bi => [bi.building, lookupGoodIconUrl(bi.good)])
);

export function lookupBuildingIconUrl(building: ProductionBuilding): string {
  return productionBuildingToIconUrl.get(building)
    ?? 'https://static.wikia.nocookie.net/anno1800/images/c/ce/Sir_Archibald_Blake.png';
}

const boostTypeToImageUrl = new Map<BoostType, string>([
  [BoostType.Electricity, 'https://static.wikia.nocookie.net/anno1800/images/0/05/Electricity.png'],
  [BoostType.TracktorBarn, 'https://static.wikia.nocookie.net/anno1800/images/6/6a/TractorBarn.png'],
  [BoostType.Silo, 'https://static.wikia.nocookie.net/anno1800/images/5/5f/Silo.png'],
  [BoostType.Fertilizer, 'https://static.wikia.nocookie.net/anno1800/images/3/3f/Dung.png'],
]);

export function lookupBoostIconUrl(boost: BoostType): string {
  return boostTypeToImageUrl.get(boost) ?? '';
}

const regionToImageUrl = new Map<Region, string>([
  [Region.OldWorld, 'https://static.wikia.nocookie.net/anno1800/images/a/a7/Icon_session_moderate_0.png'],
  [Region.NewWorld, 'https://static.wikia.nocookie.net/anno1800/images/a/a2/Icon_session_southamerica_0.png'],
  [Region.CapeTrelawney, 'https://static.wikia.nocookie.net/anno1800/images/8/8e/Icon_session_sunken_treasure.png'],
  [Region.Arctic, 'https://static.wikia.nocookie.net/anno1800/images/7/7f/Icon_session_passage_0.png'],
  [Region.Enbesa, 'https://static.wikia.nocookie.net/anno1800/images/1/1f/Icon_session_land_of_lions_0.png'],
]);

export function lookupRegionIconUrl(region: Region): string {
  return regionToImageUrl.get(region) ?? '';
}

const policyToImageUrl = new Map<DepartmentOfLaborPolicy, string>([
  [DepartmentOfLaborPolicy.LandReformAct, 'https://static.wikia.nocookie.net/anno1800/images/7/7d/Icon_agricultural_subsidy.png'],
  [DepartmentOfLaborPolicy.SkilledLaborAct, 'https://static.wikia.nocookie.net/anno1800/images/3/31/Icon_manufacturing_reform.png'],
  [DepartmentOfLaborPolicy.GalvanicGrantsAct, 'https://static.wikia.nocookie.net/anno1800/images/5/5d/Icon_efficiency_program.png'],
  [DepartmentOfLaborPolicy.FactoryInspectionsAct, 'https://static.wikia.nocookie.net/anno1800/images/5/54/Icon_professional_development.png'],
  [DepartmentOfLaborPolicy.UnionSubsidiesAct, 'https://static.wikia.nocookie.net/anno1800/images/9/96/Icon_union_impulse.png'],
]);


export function lookupPolicyIconUrl(policy: DepartmentOfLaborPolicy): string {
  return policyToImageUrl.get(policy) ?? '';
}