import { IslandView } from "../mvc/views";
import { ProductionBuilding, ProductionType, Good, Region, DepartmentOfLaborPolicy, Boost } from "./enums";

export interface ProductionInfo {
  building: ProductionBuilding;
  processingTimeSeconds: number;
  productionType: ProductionType;
  good: Good;
  inputGoods?: Good[];
  allowedRegions: Region[];
  requiresElectricity?: boolean;
};

export const improvedByLandReformAct = new Set<ProductionBuilding>([
  ProductionBuilding.GrainFarm,
  ProductionBuilding.HopFarm,
  ProductionBuilding.PotatoFarm,
  ProductionBuilding.RedPepperFarm,
  ProductionBuilding.Vineyard,
  ProductionBuilding.SheepFarm,
  ProductionBuilding.PigFarm,
  ProductionBuilding.CattleFarm,
]);

export const improvedBySkilledLaborAct = new Set<ProductionBuilding>([
  ProductionBuilding.Steelworks,
  ProductionBuilding.Furnace,
  ProductionBuilding.CharcoalKiln,
  ProductionBuilding.WeaponFactory,
  ProductionBuilding.HeavyWeaponsFactory,
  ProductionBuilding.Steelworks,
  ProductionBuilding.CabAssemblyLine,
  ProductionBuilding.BrassSmeltery,
  ProductionBuilding.OilRefinery,
  ProductionBuilding.AssemblyLineElevators,
  ProductionBuilding.AssemblyLineBiscuits,
  ProductionBuilding.AssemblyLineTypewriters,
  ProductionBuilding.ChemicalPlantShampoo,
  ProductionBuilding.ChemicalPlantLemonade,
  ProductionBuilding.ChemicalPlantSouvenirs,
  ProductionBuilding.ChemicalPlantLacquer,
]);

export function computeExtraGoodsModifier(productionBuilding: ProductionBuilding, good: Good, island: IslandView): number {
  const productionInfo = lookupProductionInfo(productionBuilding);
  if (productionInfo == null || good != productionInfo.good) {
    return 1.0;
  } else if (improvedByLandReformAct.has(productionBuilding) && island.dolPolicy == DepartmentOfLaborPolicy.LandReformAct) {
    return 1.5;
  } else if (improvedBySkilledLaborAct.has(productionBuilding) && island.dolPolicy == DepartmentOfLaborPolicy.SkilledLaborAct) {
    return 1. + 1. / 3.;
  } else {
    return 1.0;
  }
}

export function lookupProductionInfo(building: ProductionBuilding): ProductionInfo | undefined {
  return builingsToInfo.get(building);
};

export function requiresElectricity(building: ProductionBuilding): boolean {
  return builingsToInfo.get(building)?.requiresElectricity ?? false;
}

export function lookupAllowedBoosts(building: ProductionBuilding): Boost[] {
  const info = lookupProductionInfo(building);
  if (!info || info.allowedRegions.indexOf(Region.Enbesa) != -1) {
    return [];
  }
  if (info.productionType == ProductionType.AnimalFarm) {
    return [Boost.Silo];
  } else if (info.productionType == ProductionType.Factory) {
    return [Boost.Electricity];
  } else if (info.productionType == ProductionType.Mine) {
    return [Boost.Electricity];
  } else if (info.productionType == ProductionType.PlantFarm) {
    return [Boost.TracktorBarn, Boost.Fertilizer];
  }
  return [];
}

export const buildingInfo: ProductionInfo[] = [
  {
    building: ProductionBuilding.AdvancedCoffeeRoaster,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Coffee,
    inputGoods: [Good.Malt],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.AdvancedCottonMill,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.CottonFabric,
    inputGoods: [Good.Wool],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.AdvancedRumDistillery,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Rum,
    inputGoods: [Good.Potatoes],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.AlpacaFarm,
    processingTimeSeconds: 30,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.AlpacaWool,
  },
  {
    building: ProductionBuilding.Apiary,
    processingTimeSeconds: 30,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.Beeswax,
  },
  {
    building: ProductionBuilding.ArcticGasMine,
    processingTimeSeconds: 4.5 * 60,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.Arctic],
    good: Good.ArcticGas,
  },
  {
    building: ProductionBuilding.ArtisanalKitchen,
    processingTimeSeconds: 120,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Goulash,
    inputGoods: [Good.Beef, Good.RedPeppers],
  },
  {
    building: ProductionBuilding.AssemblyLineBiscuits,
    processingTimeSeconds: 15,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Biscuits,
    inputGoods: [Good.Tallow, Good.Flour, Good.Citrus],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.AssemblyLineElevators,
    processingTimeSeconds: 15,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Elevators,
    inputGoods: [Good.Steel, Good.WoodVeneers, Good.SteamMotors],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.AssemblyLineTypewriters,
    processingTimeSeconds: 15,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Typewriters,
    inputGoods: [Good.Steel, Good.Brass, Good.Lacquer],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.Bakery,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Bread,
    inputGoods: [Good.Flour],
  },
  {
    building: ProductionBuilding.BearHuntingCabin,
    processingTimeSeconds: 90,
    productionType: ProductionType.HuntingCabin,
    allowedRegions: [Region.Arctic],
    good: Good.BearFur,
  },
  {
    building: ProductionBuilding.BicycleFactory,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.PennyFarthings,
    inputGoods: [Good.Steel, Good.Caoutchouc],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.BombinWeaver,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.BowlerHats,
    inputGoods: [Good.CottonFabric, Good.Felt],
  },
  {
    building: ProductionBuilding.BrassSmeltery,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Brass,
    inputGoods: [Good.Copper, Good.Zinc],
  },
  {
    building: ProductionBuilding.Brewery,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Beer,
    inputGoods: [Good.Malt, Good.Hops],
  },
  {
    building: ProductionBuilding.BrickDryHouse,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Enbesa],
    good: Good.MudBricks,
    inputGoods: [Good.Clay, Good.Teff],
  },
  {
    building: ProductionBuilding.BrickFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.Bricks,
    inputGoods: [Good.Clay],
  },
  {
    building: ProductionBuilding.CabAssemblyLine,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.SteamCarriages,
    inputGoods: [Good.SteamMotors, Good.Chassis],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.Cannery,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.CannedFood,
    inputGoods: [Good.Goulash, Good.Iron],
  },
  {
    building: ProductionBuilding.CaoutchoucPlantation,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.Caoutchouc,
  },
  {
    building: ProductionBuilding.CaribouHuntingCabin,
    processingTimeSeconds: 60,
    productionType: ProductionType.HuntingCabin,
    allowedRegions: [Region.Arctic],
    good: Good.CaribouMeat,
  },
  {
    building: ProductionBuilding.CattleFarm,
    processingTimeSeconds: 120,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.Beef,
  },
  {
    building: ProductionBuilding.ChampagneCellar,
    processingTimeSeconds: 30,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Champagne,
    inputGoods: [Good.Grapes, Good.Glass],
  },
  {
    building: ProductionBuilding.CharcoalKiln,
    processingTimeSeconds: 30,
    productionType: ProductionType.Orchard,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld, Region.Arctic],
    good: Good.Coal,
  },
  {
    building: ProductionBuilding.ChemicalPlantEthanol,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Ethanol,
    inputGoods: [Good.Wood, Good.Corn],
  },
  {
    building: ProductionBuilding.ChemicalPlantShampoo,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Shampoo,
    inputGoods: [Good.CoconutOil, Good.Cinnamon, Good.Soap],
  },
  {
    building: ProductionBuilding.ChemicalPlantLemonade,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Lemonade,
    inputGoods: [Good.Sugar, Good.Citrus, Good.Saltpetre],
  },
  {
    building: ProductionBuilding.ChemicalPlantSouvenirs,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Souvenirs,
    inputGoods: [Good.CamphorWax, Good.Glass, Good.Cotton],
  },
  {
    building: ProductionBuilding.ChemicalPlantLacquer,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Lacquer,
    inputGoods: [Good.QuartzSand, Good.Resin, Good.Ethanol],
  },
  {
    building: ProductionBuilding.ChocolateFactory,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Chocolate,
    inputGoods: [Good.Cocoa, Good.Sugar],
  },
  {
    building: ProductionBuilding.CigarFactory,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Cigars,
    inputGoods: [Good.Tobacco, Good.WoodVeneers],
  },
  {
    building: ProductionBuilding.ClayPit,
    processingTimeSeconds: 30,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.Clay,
  },
  {
    building: ProductionBuilding.Clockmakers,
    processingTimeSeconds: 45,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.PocketWatches,
    inputGoods: [Good.Gold, Good.Glass],
  },
  {
    building: ProductionBuilding.Coachmakers,
    processingTimeSeconds: 120,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Chassis,
    inputGoods: [Good.Wood, Good.Caoutchouc],
  },
  {
    building: ProductionBuilding.CoalMine,
    processingTimeSeconds: 15,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Coal,
  },
  {
    building: ProductionBuilding.CocoaPlantation,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.Cocoa,
  },
  {
    building: ProductionBuilding.CoffeePlantation,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.CoffeeBeans,
  },
  {
    building: ProductionBuilding.CoffeeRoaster,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Coffee,
    inputGoods: [Good.CoffeeBeans],
  },
  {
    building: ProductionBuilding.ConcreteFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.ReinforcedConcrete,
    inputGoods: [Good.Steel, Good.Cement],
  },
  {
    building: ProductionBuilding.CopperMine,
    processingTimeSeconds: 30,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Copper,
  },
  {
    building: ProductionBuilding.CornFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.Corn,
  },
  {
    building: ProductionBuilding.CottonMill,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.CottonFabric,
    inputGoods: [Good.Cotton],
  },
  {
    building: ProductionBuilding.CottonPlantation,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.Cotton,
  },
  {
    building: ProductionBuilding.DynamiteFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Dynamite,
    inputGoods: [Good.Tallow, Good.Saltpetre],
  },
  {
    building: ProductionBuilding.FilamentFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Filaments,
    inputGoods: [Good.Coal],
  },
  {
    building: ProductionBuilding.Fishery,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Fish,
  },
  {
    building: ProductionBuilding.FishOilFactory,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.FishOil,
  },
  {
    building: ProductionBuilding.FlourMill,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Flour,
    inputGoods: [Good.Grain],
  },
  {
    building: ProductionBuilding.FrameworkKnitters,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.WorkClothes,
    inputGoods: [Good.Wool],
  },
  {
    building: ProductionBuilding.FriedPlantainKitchen,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.FriedPlantains,
    inputGoods: [Good.Plantains, Good.FishOil],
  },
  {
    building: ProductionBuilding.FurDealer,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.FurCoats,
    inputGoods: [Good.CottonFabric, Good.Furs],
  },
  {
    building: ProductionBuilding.Furnace,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Steel,
    inputGoods: [Good.Iron, Good.Coal],
  },
  {
    building: ProductionBuilding.Glassmakers,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Glass,
    inputGoods: [Good.QuartzSand],
  },
  {
    building: ProductionBuilding.GoatFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.GoatMilk,
  },
  {
    building: ProductionBuilding.GoldOreMine,
    processingTimeSeconds: 150,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.NewWorld],
    good: Good.GoldOre,
  },
  {
    building: ProductionBuilding.Goldsmiths,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Gold,
    inputGoods: [Good.GoldOre, Good.Coal],
  },
  {
    building: ProductionBuilding.GooseFarm,
    processingTimeSeconds: 120,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.Arctic],
    good: Good.GooseFeathers,
  },
  {
    building: ProductionBuilding.GrainFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Grain,
  },
  {
    building: ProductionBuilding.GramophoneFactory,
    processingTimeSeconds: 120,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Gramophones,
    inputGoods: [Good.WoodVeneers, Good.Brass],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.HeavyWeaponsFactory,
    processingTimeSeconds: 120,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.AdvancedWeapons,
    inputGoods: [Good.Dynamite, Good.Steel],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.HibiscusFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.HibiscusPetals,
  },
  {
    building: ProductionBuilding.HopFarm,
    processingTimeSeconds: 90,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Hops,
  },
  {
    building: ProductionBuilding.HuntingCabin,
    processingTimeSeconds: 60,
    productionType: ProductionType.HuntingCabin,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Furs,
  },
  {
    building: ProductionBuilding.HuskyFarm,
    processingTimeSeconds: 120,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.Arctic],
    good: Good.Huskies,
  },
  {
    building: ProductionBuilding.HuskySledFactory,
    processingTimeSeconds: 120,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.HuskySleds,
    inputGoods: [Good.Huskies, Good.Sleds],
  },
  {
    building: ProductionBuilding.IndigoFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.IndigoDye,
  },
  {
    building: ProductionBuilding.IronMine,
    processingTimeSeconds: 15,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.Iron,
  },
  {
    building: ProductionBuilding.Jewellers,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Jewellery,
    inputGoods: [Good.Gold, Good.Pearls],
  },
  {
    building: ProductionBuilding.LightBulbFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.LightBulbs,
    inputGoods: [Good.Filaments, Good.Glass],
  },
  {
    building: ProductionBuilding.LimestoneQuarry,
    processingTimeSeconds: 30,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Cement,
  },
  {
    building: ProductionBuilding.LinenMill,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Enbesa],
    good: Good.Linen,
    inputGoods: [Good.Linseed],
  },
  {
    building: ProductionBuilding.LinseedFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.Linseed,
  },
  {
    building: ProductionBuilding.LobsterFishery,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Enbesa],
    good: Good.Lobster,
  },
  {
    building: ProductionBuilding.LumberjacksHut,
    processingTimeSeconds: 15,
    productionType: ProductionType.Orchard,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.Wood,
  },
  {
    building: ProductionBuilding.Malthouse,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Malt,
    inputGoods: [Good.Grain],
  },
  {
    building: ProductionBuilding.MarquetryWorkshop,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.WoodVeneers,
    inputGoods: [Good.Wood],
  },
  {
    building: ProductionBuilding.MotorAssemblyLine,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.SteamMotors,
    inputGoods: [Good.Steel, Good.Brass],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.OilLampFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.OilLamps,
    inputGoods: [Good.Brass, Good.WhaleOil],
  },
  {
    building: ProductionBuilding.OilRefinery,
    processingTimeSeconds: 15,
    productionType: ProductionType.Oil,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld],
    good: Good.Oil,
  },
  {
    building: ProductionBuilding.OrchardCherryWood,
    processingTimeSeconds: 30,
    productionType: ProductionType.Orchard,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.CherryWood,
  },
  {
    building: ProductionBuilding.OrchardCinnamon,
    processingTimeSeconds: 30,
    productionType: ProductionType.Orchard,
    allowedRegions: [Region.NewWorld],
    good: Good.Cinnamon,
  },
  {
    building: ProductionBuilding.OrchardCitrus,
    processingTimeSeconds: 30,
    productionType: ProductionType.Orchard,
    allowedRegions: [Region.NewWorld],
    good: Good.Citrus,
  },
  {
    building: ProductionBuilding.OrchardCoconutOil,
    processingTimeSeconds: 30,
    productionType: ProductionType.Orchard,
    allowedRegions: [Region.NewWorld],
    good: Good.CoconutOil,
  },
  {
    building: ProductionBuilding.OrchardJam,
    processingTimeSeconds: 30,
    productionType: ProductionType.Orchard,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Jam,
  },
  {
    building: ProductionBuilding.OrchardResin,
    processingTimeSeconds: 30,
    productionType: ProductionType.Orchard,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Resin,
  },
  {
    building: ProductionBuilding.PaperMill,
    processingTimeSeconds: 15,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Enbesa],
    good: Good.Paper,
    inputGoods: [Good.Wood],
  },
  {
    building: ProductionBuilding.ParkaFactory,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.Parkas,
    inputGoods: [Good.BearFur, Good.SealSkin],
  },
  {
    building: ProductionBuilding.PearlFarm,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Pearls,
  },
  {
    building: ProductionBuilding.PemmicanCookhouse,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.Pemmican,
    inputGoods: [Good.WhaleOil, Good.CaribouMeat],
  },
  {
    building: ProductionBuilding.PigFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Pigs,
  },
  {
    building: ProductionBuilding.PlantainPlantation,
    processingTimeSeconds: 30,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.Plantains,
  },
  {
    building: ProductionBuilding.PonchoDarner,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Ponchos,
    inputGoods: [Good.AlpacaWool],
  },
  {
    building: ProductionBuilding.PotatoFarm,
    processingTimeSeconds: 30,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Potatoes,
  },
  {
    building: ProductionBuilding.PrimeHuntingCabin,
    processingTimeSeconds: 15,
    productionType: ProductionType.HuntingCabin,
    allowedRegions: [Region.Arctic],
    good: Good.Furs,
  },
  {
    building: ProductionBuilding.RedPepperFarm,
    processingTimeSeconds: 120,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.RedPeppers,
  },
  {
    building: ProductionBuilding.RenderingWorks,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Tallow,
    inputGoods: [Good.Pigs],
  },
  {
    building: ProductionBuilding.RumDistillery,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Rum,
    inputGoods: [Good.SugarCane, Good.Wood],
  },
  {
    building: ProductionBuilding.Sailmakers,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Sails,
    inputGoods: [Good.Wool],
  },
  {
    building: ProductionBuilding.SaltWorks,
    processingTimeSeconds: 90,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.Enbesa],
    good: Good.Salt,
  },
  {
    building: ProductionBuilding.SaltpeterWorks,
    processingTimeSeconds: 120,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Saltpetre,
  },
  {
    building: ProductionBuilding.SandMine,
    processingTimeSeconds: 30,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.QuartzSand,
  },
  {
    building: ProductionBuilding.Sawmill,
    processingTimeSeconds: 15,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney, Region.NewWorld, Region.Arctic],
    good: Good.Timber,
    inputGoods: [Good.Wood],
  },
  {
    building: ProductionBuilding.SealHuntingDocks,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.SealSkin,
  },
  {
    building: ProductionBuilding.SchnappsDistillery,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Schnapps,
    inputGoods: [Good.Potatoes],
  },
  {
    building: ProductionBuilding.SewingMachineFactory,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.SewingMachines,
    inputGoods: [Good.Steel, Good.Wood],
  },
  {
    building: ProductionBuilding.SheepFarm,
    processingTimeSeconds: 30,
    productionType: ProductionType.AnimalFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Wool,
  },
  {
    building: ProductionBuilding.Slaughterhouse,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Sausages,
    inputGoods: [Good.Pigs],
  },
  {
    building: ProductionBuilding.SledFrameFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.Sleds,
    inputGoods: [Good.SealSkin, Good.Wood],
  },
  {
    building: ProductionBuilding.SleepingBagFactory,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.SleepingBags,
    inputGoods: [Good.SealSkin, Good.GooseFeathers],
  },
  {
    building: ProductionBuilding.SoapFactory,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Soap,
    inputGoods: [Good.Tallow],
  },
  {
    building: ProductionBuilding.SpectacleFactory,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Glasses,
    inputGoods: [Good.Glass, Good.Brass],
  },
  {
    building: ProductionBuilding.SpiceFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.Spices,
  },
  {
    building: ProductionBuilding.Steelworks,
    processingTimeSeconds: 45,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.SteelBeams,
    inputGoods: [Good.Steel],
  },
  {
    building: ProductionBuilding.SugarCanePlantation,
    processingTimeSeconds: 30,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.SugarCane,
  },
  {
    building: ProductionBuilding.SugarRefinery,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Sugar,
    inputGoods: [Good.SugarCane],
  },
  {
    building: ProductionBuilding.TapestryLooms,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Enbesa],
    good: Good.Tapestries,
    inputGoods: [Good.Linen, Good.IndigoDye],
  },
  {
    building: ProductionBuilding.TailorsShop,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.TailoredSuits,
    inputGoods: [Good.CottonFabric, Good.Linen],
  },
  {
    building: ProductionBuilding.TeaSpicer,
    processingTimeSeconds: 90,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.HibiscusTea,
    inputGoods: [Good.HibiscusPetals],
  },
  {
    building: ProductionBuilding.TeffFarm,
    processingTimeSeconds: 60,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.Enbesa],
    good: Good.Teff,
  },
  {
    building: ProductionBuilding.TelephoneManufacturer,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Telephones,
    inputGoods: [Good.Filaments, Good.WoodVeneers],
    requiresElectricity: true,
  },
  {
    building: ProductionBuilding.TobaccoPlantation,
    processingTimeSeconds: 120,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.NewWorld],
    good: Good.Tobacco,
  },
  {
    building: ProductionBuilding.TortillaMaker,
    processingTimeSeconds: 30,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.NewWorld],
    good: Good.Tortillas,
    inputGoods: [Good.Corn, Good.Beef],
  },
  {
    building: ProductionBuilding.Vineyard,
    processingTimeSeconds: 120,
    productionType: ProductionType.PlantFarm,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Grapes,
  },
  {
    building: ProductionBuilding.WeaponFactory,
    processingTimeSeconds: 90,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Weapons,
    inputGoods: [Good.Steel],
  },
  {
    building: ProductionBuilding.WhalingStation,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.Arctic],
    good: Good.WhaleOil,
  },
  {
    building: ProductionBuilding.WindowMakers,
    processingTimeSeconds: 60,
    productionType: ProductionType.Factory,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Windows,
    inputGoods: [Good.Glass, Good.Wood],
  },
  {
    building: ProductionBuilding.ZincMine,
    processingTimeSeconds: 30,
    productionType: ProductionType.Mine,
    allowedRegions: [Region.OldWorld, Region.CapeTrelawney],
    good: Good.Zinc,
  },
];

const builingsToInfo = new Map<ProductionBuilding, ProductionInfo>(buildingInfo.map(i => [i.building, i]));


