import { Good, ProductionBuilding, Boost, Region, DepartmentOfLaborPolicy } from "./enums";
import { buildingInfo } from "./facts";

export function lookupGoodIconUrl(good: Good): string {
  return goodsToIconUrl.get(good)
    ?? 'https://static.wikia.nocookie.net/anno1800/images/c/ce/Sir_Archibald_Blake.png';
}

export function lookupBuildingIconUrl(building: ProductionBuilding): string {
  return productionBuildingToIconUrl.get(building)
    ?? 'https://static.wikia.nocookie.net/anno1800/images/c/ce/Sir_Archibald_Blake.png';
}
export function lookupBoostIconUrl(boost: Boost): string {
  return boostTypeToImageUrl.get(boost) ?? '';
}
export function lookupRegionIconUrl(region: Region): string {
  return regionToImageUrl.get(region) ?? '';
}
export function lookupPolicyIconUrl(policy: DepartmentOfLaborPolicy): string {
  return policyToImageUrl.get(policy) ?? '';
}

const goodsToIconUrl = new Map<Good, string>([
  [Good.Unknown, ''],
  [Good.AdvancedWeapons, 'https://static.wikia.nocookie.net/anno1800/images/3/30/Advanced_weapons.png'],
  [Good.AlpacaWool, 'https://static.wikia.nocookie.net/anno1800/images/a/a6/Alpaca_wool.png'],
  [Good.AluminiumProfiles, 'https://static.wikia.nocookie.net/anno1800/images/2/24/Aluminium_Profiles.png'],
  [Good.ArcticGas, 'https://static.wikia.nocookie.net/anno1800/images/e/e5/Arctic_Gas.png'],
  [Good.Bauxite, 'https://static.wikia.nocookie.net/anno1800/images/1/11/Bauxite.png'],
  [Good.BearFur, 'https://static.wikia.nocookie.net/anno1800/images/7/72/Bear_Fur.png'],
  [Good.Beef, 'https://static.wikia.nocookie.net/anno1800/images/a/af/Beef.png'],
  [Good.Beer, 'https://static.wikia.nocookie.net/anno1800/images/b/b3/Beer.png'],
  [Good.Beeswax, 'https://static.wikia.nocookie.net/anno1800/images/7/70/Icon_beeswax_0.png'],
  [Good.Biscuits, 'https://static.wikia.nocookie.net/anno1800/images/f/f5/Biscuits.png'],
  [Good.Bombs, 'https://static.wikia.nocookie.net/anno1800/images/c/cc/Bombs.png'],
  [Good.BowlerHats, 'https://static.wikia.nocookie.net/anno1800/images/d/db/Bowler_hats.png'],
  [Good.Brass, 'https://static.wikia.nocookie.net/anno1800/images/d/de/Brass.png'],
  [Good.Bread, 'https://static.wikia.nocookie.net/anno1800/images/e/e1/Bread.png'],
  [Good.Bricks, 'https://static.wikia.nocookie.net/anno1800/images/f/ff/Bricks.png'],
  [Good.CamphorWax, 'https://static.wikia.nocookie.net/anno1800/images/3/30/Camphor_Wax.png'],
  [Good.CannedFood, 'https://static.wikia.nocookie.net/anno1800/images/c/c8/Canned_food.png'],
  [Good.Caoutchouc, 'https://static.wikia.nocookie.net/anno1800/images/5/52/Caoutchouc.png'],
  [Good.CaribouMeat, 'https://static.wikia.nocookie.net/anno1800/images/e/e9/Caribou_Meat.png'],
  [Good.Cement, 'https://static.wikia.nocookie.net/anno1800/images/d/de/Cement.png'],
  [Good.Champagne, 'https://static.wikia.nocookie.net/anno1800/images/0/05/Champagne.png'],
  [Good.CherryWood, 'https://static.wikia.nocookie.net/anno1800/images/8/8e/Cherry_Wood.png'],
  [Good.Chocolate, 'https://static.wikia.nocookie.net/anno1800/images/d/df/Chocolate.png'],
  [Good.Cigars, 'https://static.wikia.nocookie.net/anno1800/images/8/87/Cigars.png'],
  [Good.Cinnamon, 'https://static.wikia.nocookie.net/anno1800/images/1/1b/Cinnamon.png'],
  [Good.Citrus, 'https://static.wikia.nocookie.net/anno1800/images/b/b4/Citrus.png'],
  [Good.Clay, 'https://static.wikia.nocookie.net/anno1800/images/a/a2/Clay.png'],
  [Good.Chassis, 'https://static.wikia.nocookie.net/anno1800/images/d/dd/Chassis.png'],
  [Good.Coal, 'https://static.wikia.nocookie.net/anno1800/images/a/a7/Coal.png'],
  [Good.Cocoa, 'https://static.wikia.nocookie.net/anno1800/images/8/8d/Cocoa.png'],
  [Good.CoconutOil, 'https://static.wikia.nocookie.net/anno1800/images/e/e6/Coconut_Oil.png'],
  [Good.Coffee, 'https://static.wikia.nocookie.net/anno1800/images/e/e9/Coffee.png'],
  [Good.CoffeeBeans, 'https://static.wikia.nocookie.net/anno1800/images/6/6e/Coffee_beans.png'],
  [Good.Copper, 'https://static.wikia.nocookie.net/anno1800/images/1/12/Copper.png'],
  [Good.Corn, 'https://static.wikia.nocookie.net/anno1800/images/f/f8/Corn.png'],
  [Good.Cotton, 'https://static.wikia.nocookie.net/anno1800/images/c/c3/Cotton.png'],
  [Good.CottonFabric, 'https://static.wikia.nocookie.net/anno1800/images/1/15/Cotton_fabric.png'],
  [Good.Dynamite, 'https://static.wikia.nocookie.net/anno1800/images/f/fc/Dynamite.png'],
  [Good.Elevators, 'https://static.wikia.nocookie.net/anno1800/images/d/db/Elevators.png'],
  [Good.Ethanol, 'https://static.wikia.nocookie.net/anno1800/images/9/95/Ethanol.png'],
  [Good.Felt, 'https://static.wikia.nocookie.net/anno1800/images/b/b0/Felt.png'],
  [Good.Filaments, 'https://static.wikia.nocookie.net/anno1800/images/d/d8/Filaments.png'],
  [Good.Fish, 'https://static.wikia.nocookie.net/anno1800/images/f/fb/Fish.png'],
  [Good.FishOil, 'https://static.wikia.nocookie.net/anno1800/images/e/ea/Fish_Oil.png'],
  [Good.Flour, 'https://static.wikia.nocookie.net/anno1800/images/e/e8/Flour.png'],
  [Good.FriedPlantains, 'https://static.wikia.nocookie.net/anno1800/images/5/58/Fried_plantains.png'],
  [Good.FurCoats, 'https://static.wikia.nocookie.net/anno1800/images/8/85/Fur_Coats.png'],
  [Good.Furs, 'https://static.wikia.nocookie.net/anno1800/images/8/88/Furs.png'],
  [Good.Glass, 'https://static.wikia.nocookie.net/anno1800/images/1/15/Glass.png'],
  [Good.Glasses, 'https://static.wikia.nocookie.net/anno1800/images/b/b4/Glasses.png'],
  [Good.GoatMilk, 'https://static.wikia.nocookie.net/anno1800/images/7/7b/Icon_goat_milk_0.png'],
  [Good.Gold, 'https://static.wikia.nocookie.net/anno1800/images/1/10/Gold.png'],
  [Good.GoldOre, 'https://static.wikia.nocookie.net/anno1800/images/f/f7/Gold_Ore.png'],
  [Good.GooseFeathers, 'https://static.wikia.nocookie.net/anno1800/images/8/82/Goose_Feathers.png'],
  [Good.Goulash, 'https://static.wikia.nocookie.net/anno1800/images/5/5e/Goulash.png'],
  [Good.Grain, 'https://static.wikia.nocookie.net/anno1800/images/6/66/Grain.png'],
  [Good.Grapes, 'https://static.wikia.nocookie.net/anno1800/images/3/39/Grapes.png'],
  [Good.Gramophones, 'https://static.wikia.nocookie.net/anno1800/images/0/0e/Gramophone.png'],
  [Good.Helium, 'https://static.wikia.nocookie.net/anno1800/images/5/57/Helium.png'],
  [Good.Herbs, 'https://static.wikia.nocookie.net/anno1800/images/7/79/Herbs.png'],
  [Good.HibiscusPetals, 'https://static.wikia.nocookie.net/anno1800/images/0/04/Icon_hibiscus_farm_0.png'],
  [Good.HibiscusTea, 'https://static.wikia.nocookie.net/anno1800/images/6/69/Icon_hibiscus_tea_0.png'],
  [Good.Hops, 'https://static.wikia.nocookie.net/anno1800/images/5/59/Hops.png'],
  [Good.Huskies, 'https://static.wikia.nocookie.net/anno1800/images/4/4b/Huskies.png'],
  [Good.HuskySleds, 'https://static.wikia.nocookie.net/anno1800/images/5/59/Husky_Sleds.png'],
  [Good.IceCream, 'https://static.wikia.nocookie.net/anno1800/images/5/5d/Ice_Cream.png'],
  [Good.IndigoDye, 'https://static.wikia.nocookie.net/anno1800/images/1/1b/Icon_indigo_0.png'],
  [Good.Iron, 'https://static.wikia.nocookie.net/anno1800/images/4/45/Iron.png'],
  [Good.Jam, 'https://static.wikia.nocookie.net/anno1800/images/f/fa/Jam.png'],
  [Good.Jewellery, 'https://static.wikia.nocookie.net/anno1800/images/7/7b/Jewelry.png'],
  [Good.Lacquer, 'https://static.wikia.nocookie.net/anno1800/images/4/4c/Lacquer.png'],
  [Good.LeatherBoots, 'https://static.wikia.nocookie.net/anno1800/images/c/c4/Icon_leather_shoes_0.png'],
  [Good.Lemonade, 'https://static.wikia.nocookie.net/anno1800/images/2/2a/Lemonade.png'],
  [Good.LightBulbs, 'https://static.wikia.nocookie.net/anno1800/images/0/06/Light_bulb.png'],
  [Good.Linen, 'https://static.wikia.nocookie.net/anno1800/images/9/9a/Icon_linen_fabric_0.png'],
  [Good.Linseed, 'https://static.wikia.nocookie.net/anno1800/images/6/65/Icon_linen_farm_0.png'],
  [Good.Lobster, 'https://static.wikia.nocookie.net/anno1800/images/9/91/Icon_seafood_0.png'],
  [Good.Malt, 'https://static.wikia.nocookie.net/anno1800/images/d/de/Malt.png'],
  [Good.Milk, 'https://static.wikia.nocookie.net/anno1800/images/9/92/Milk.png'],
  [Good.Minerals, 'https://static.wikia.nocookie.net/anno1800/images/1/10/Minerals.png'],
  [Good.MudBricks, 'https://static.wikia.nocookie.net/anno1800/images/a/ab/Icon_mud_bricks_0.png'],
  [Good.NanduFeathers, 'https://static.wikia.nocookie.net/anno1800/images/4/4c/Nandu_Feathers.png'],
  [Good.NanduLeather, 'https://static.wikia.nocookie.net/anno1800/images/f/fc/Nandu_Leather.png'],
  [Good.Oil, 'https://static.wikia.nocookie.net/anno1800/images/0/06/Oil.png'],
  [Good.OilLamps, 'https://static.wikia.nocookie.net/anno1800/images/5/57/Oil_Lamps.png'],
  [Good.Pamphlets, 'https://static.wikia.nocookie.net/anno1800/images/c/c5/Pamphlets.png'],
  [Good.Paper, 'https://static.wikia.nocookie.net/anno1800/images/1/1d/Icon_paper_0.png'],
  [Good.Parkas, 'https://static.wikia.nocookie.net/anno1800/images/d/d6/Parkas.png'],
  [Good.Pearls, 'https://static.wikia.nocookie.net/anno1800/images/7/76/Pearls.png'],
  [Good.Pemmican, 'https://static.wikia.nocookie.net/anno1800/images/3/33/Pemmican.png'],
  [Good.PennyFarthings, 'https://static.wikia.nocookie.net/anno1800/images/b/b9/High_wheeler.png'],
  [Good.Perfumes, 'https://static.wikia.nocookie.net/anno1800/images/7/71/Perfumes.png'],
  [Good.Pigs, 'https://static.wikia.nocookie.net/anno1800/images/e/e3/Pigs.png'],
  [Good.Plantains, 'https://static.wikia.nocookie.net/anno1800/images/c/c4/Plantains.png'],
  [Good.PocketWatches, 'https://static.wikia.nocookie.net/anno1800/images/b/be/Pocket_watch.png'],
  [Good.Ponchos, 'https://static.wikia.nocookie.net/anno1800/images/2/27/Poncho.png'],
  [Good.Potatoes, 'https://static.wikia.nocookie.net/anno1800/images/c/c2/Potato.png'],
  [Good.QuartzSand, 'https://static.wikia.nocookie.net/anno1800/images/5/50/Quartz_sand.png'],
  [Good.RedPeppers, 'https://static.wikia.nocookie.net/anno1800/images/c/cf/Red_peppers.png'],
  [Good.ReinforcedConcrete, 'https://static.wikia.nocookie.net/anno1800/images/7/7a/Reinforced_concrete.png'],
  [Good.Resin, 'https://static.wikia.nocookie.net/anno1800/images/2/2c/Resin.png'],
  [Good.Rum, 'https://static.wikia.nocookie.net/anno1800/images/6/61/Rum.png'],
  [Good.Sails, 'https://static.wikia.nocookie.net/anno1800/images/2/22/Sails.png'],
  [Good.Salt, 'https://static.wikia.nocookie.net/anno1800/images/7/77/Salt.png'],
  [Good.Saltpetre, 'https://static.wikia.nocookie.net/anno1800/images/d/d7/Saltpeter.png'],
  [Good.SangaCow, 'https://static.wikia.nocookie.net/anno1800/images/5/51/Icon_watusi_0.png'],
  [Good.Sausages, 'https://static.wikia.nocookie.net/anno1800/images/a/a0/Sausages.png'],
  [Good.Schnapps, 'https://static.wikia.nocookie.net/anno1800/images/4/47/Schnapps.png'],
  [Good.SealSkin, 'https://static.wikia.nocookie.net/anno1800/images/d/df/Seal_Skin.png'],
  [Good.SewingMachines, 'https://static.wikia.nocookie.net/anno1800/images/f/ff/Sewing_machines.png'],
  [Good.Shampoo, 'https://static.wikia.nocookie.net/anno1800/images/b/bb/Shampoo.png'],
  [Good.Sleds, 'https://static.wikia.nocookie.net/anno1800/images/f/fc/Sleds.png'],
  [Good.SleepingBags, 'https://static.wikia.nocookie.net/anno1800/images/0/0a/Sleeping_Bags.png'],
  [Good.Soap, 'https://static.wikia.nocookie.net/anno1800/images/6/65/Soap.png'],
  [Good.Souvenirs, 'https://static.wikia.nocookie.net/anno1800/images/5/56/Souvenirs.png'],
  [Good.Spices, 'https://static.wikia.nocookie.net/anno1800/images/e/ec/Icon_spices_0.png'],
  [Good.SteamCarriages, 'https://static.wikia.nocookie.net/anno1800/images/7/7c/Steam_carriages.png'],
  [Good.SteamMotors, 'https://static.wikia.nocookie.net/anno1800/images/b/b9/Steam_motors.png'],
  [Good.Steel, 'https://static.wikia.nocookie.net/anno1800/images/c/c9/Steel.png'],
  [Good.SteelBeams, 'https://static.wikia.nocookie.net/anno1800/images/5/52/Steel_beams.png'],
  [Good.Sugar, 'https://static.wikia.nocookie.net/anno1800/images/a/a9/Sugar.png'],
  [Good.SugarCane, 'https://static.wikia.nocookie.net/anno1800/images/e/e8/Sugar_cane.png'],
  [Good.TailoredSuits, 'https://static.wikia.nocookie.net/anno1800/images/6/6d/Icon_suits_0.png'],
  [Good.Tallow, 'https://static.wikia.nocookie.net/anno1800/images/f/f7/Tallow.png'],
  [Good.Tapestries, 'https://static.wikia.nocookie.net/anno1800/images/1/12/Icon_tapestries_0.png'],
  [Good.Teff, 'https://static.wikia.nocookie.net/anno1800/images/1/18/Icon_teff_grass_0.png'],
  [Good.Telephones, 'https://static.wikia.nocookie.net/anno1800/images/f/f3/Icon_telephones_0.png'],
  [Good.Timber, 'https://static.wikia.nocookie.net/anno1800/images/7/71/Timber.png'],
  [Good.Tobacco, 'https://static.wikia.nocookie.net/anno1800/images/1/19/Tobacco.png'],
  [Good.Tortillas, 'https://static.wikia.nocookie.net/anno1800/images/d/d7/Tortilla.png'],
  [Good.Toys, 'https://static.wikia.nocookie.net/anno1800/images/3/37/Toys.png'],
  [Good.Typewriters, 'https://static.wikia.nocookie.net/anno1800/images/6/6c/Typewriters.png'],
  [Good.Violins, 'https://static.wikia.nocookie.net/anno1800/images/3/3f/Violins.png'],
  [Good.WaterDrop, 'https://static.wikia.nocookie.net/anno1800/images/9/9c/Water_Drop.png'],
  [Good.Weapons, 'https://static.wikia.nocookie.net/anno1800/images/a/ae/Weapons.png'],
  [Good.WhaleOil, 'https://static.wikia.nocookie.net/anno1800/images/f/f5/Whale_Oil.png'],
  [Good.Windows, 'https://static.wikia.nocookie.net/anno1800/images/b/ba/Windows.png'],
  [Good.Wood, 'https://static.wikia.nocookie.net/anno1800/images/d/df/Wood.png'],
  [Good.WoodVeneers, 'https://static.wikia.nocookie.net/anno1800/images/8/80/Wood_veneers.png'],
  [Good.Wool, 'https://static.wikia.nocookie.net/anno1800/images/3/34/Wool.png'],
  [Good.WorkClothes, 'https://static.wikia.nocookie.net/anno1800/images/e/e9/Work_clothes.png'],
  [Good.Zinc, 'https://static.wikia.nocookie.net/anno1800/images/c/cb/Zinc.png'],
]);

const productionBuildingToIconUrl = new Map<ProductionBuilding, string>(
  buildingInfo.map(bi => [bi.building, lookupGoodIconUrl(bi.good)])
);

const boostTypeToImageUrl = new Map<Boost, string>([
  [Boost.Electricity, 'https://static.wikia.nocookie.net/anno1800/images/0/05/Electricity.png'],
  [Boost.TracktorBarn, 'https://static.wikia.nocookie.net/anno1800/images/6/6a/TractorBarn.png'],
  [Boost.Silo, 'https://static.wikia.nocookie.net/anno1800/images/5/5f/Silo.png'],
  [Boost.Fertilizer, 'https://static.wikia.nocookie.net/anno1800/images/3/3f/Dung.png'],
]);

const regionToImageUrl = new Map<Region, string>([
  [Region.OldWorld, 'https://static.wikia.nocookie.net/anno1800/images/a/a7/Icon_session_moderate_0.png'],
  [Region.NewWorld, 'https://static.wikia.nocookie.net/anno1800/images/a/a2/Icon_session_southamerica_0.png'],
  [Region.CapeTrelawney, 'https://static.wikia.nocookie.net/anno1800/images/8/8e/Icon_session_sunken_treasure.png'],
  [Region.Arctic, 'https://static.wikia.nocookie.net/anno1800/images/7/7f/Icon_session_passage_0.png'],
  [Region.Enbesa, 'https://static.wikia.nocookie.net/anno1800/images/1/1f/Icon_session_land_of_lions_0.png'],
]);

const policyToImageUrl = new Map<DepartmentOfLaborPolicy, string>([
  [DepartmentOfLaborPolicy.LandReformAct, 'https://static.wikia.nocookie.net/anno1800/images/7/7d/Icon_agricultural_subsidy.png'],
  [DepartmentOfLaborPolicy.SkilledLaborAct, 'https://static.wikia.nocookie.net/anno1800/images/3/31/Icon_manufacturing_reform.png'],
  [DepartmentOfLaborPolicy.GalvanicGrantsAct, 'https://static.wikia.nocookie.net/anno1800/images/5/5d/Icon_efficiency_program.png'],
  [DepartmentOfLaborPolicy.FactoryInspectionsAct, 'https://static.wikia.nocookie.net/anno1800/images/5/54/Icon_professional_development.png'],
  [DepartmentOfLaborPolicy.UnionSubsidiesAct, 'https://static.wikia.nocookie.net/anno1800/images/9/96/Icon_union_impulse.png'],
]);
